
services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/traefik-config"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.linode.acme.dnschallenge=true"
      - "--certificatesresolvers.linode.acme.dnschallenge.provider=linode"
      - "--certificatesresolvers.linode.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.linode.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LINODE_TOKEN=${LINODE_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-config:/traefik-config
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dash-auth@docker"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=linode"
      - "traefik.http.middlewares.dash-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    volumes:
      - ollama:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`${OLLAMA_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls.certresolver=linode"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"


  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=https://${OLLAMA_SUBDOMAIN}.${DOMAIN}/api
      - WEBUI_AUTH_MODE=${WEBUI_AUTH_MODE}
      - WEBUI_USERNAME=${WEBUI_USERNAME}
      - WEBUI_PASSWORD=${WEBUI_PASSWORD}
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webui.rule=Host(`${OPENWEBUI_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.webui.entrypoints=websecure"
      - "traefik.http.routers.webui.tls.certresolver=linode"
      - "traefik.http.services.webui.loadbalancer.server.port=8080"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=${N8N_SUBDOMAIN}.${DOMAIN}
      - N8N_PORT=443
      - N8N_PROTOCOL=https
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
    volumes:
      - n8n:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=linode"
      - "traefik.http.services.n8n.loadbalancer.server.port=443"

volumes:
  ollama:
  open-webui:
  n8n:

networks:
  default:
    name: app-network